apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
data:
  application.conf: |
    update-period: {{ .Values.updatePeriod }}

    redis {
      host: {{ .Values.redis.host | quote }}
      port: {{ .Values.redis.port | int }}
      pass: {{ .Values.redis.pass | quote }}
    }

    telegram {
      token: {{ .Values.telegram.token | quote }}
    }

  logback.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <configuration scan="true" scanPeriod="30 seconds">
        <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
            <encoder>
                <charset>UTF-8</charset>
                <pattern>
                    %yellow(%d{dd-MMM-YYYY HH:mm:ss.SSS}) %highlight(%-5level) %thread %cyan(%logger{36}) - %msg%n
                </pattern>
            </encoder>
        </appender>

        <logger name="com.github.acteek" level={{ .Values.logLevel | quote }}/>
        <logger name="org.http4s" level="WARN"/>
        <logger name="com.bot4s.telegram.clients.SttpClient" level="WARN"/>

        <root level="WARN">
            <appender-ref ref="STDOUT"/>
        </root>
    </configuration>
