addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat" % "0.4.1")
addSbtPlugin("io.spray" % "sbt-revolver" % "0.9.1")
addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "2.0.0")
addSbtPlugin("com.github.sbt"   % "sbt-native-packager"  % "1.9.11")
addSbtPlugin("com.typesafe.sbt" % "sbt-git"              % "1.0.0")
