name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  IMAGE_TAG: $GITHUB_REF_NAME-$(echo $GITHUB_SHA | head -c7)

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'sbt'
    - name: Compile
      run: sbt compile
    - name: Dockerfile generate
      run: sbt Docker/stage
    - name: Docker image build
      run: |
         docker build -t acteek/burger-termin:$IMAGE_TAG /target/docker/.
         docker push acteek/burger-termin:$IMAGE_TAG


  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@main
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # only needed if version is 'latest'
        id: install
      - name: Save DigitalOcean kubeconfig with short-lived credentials
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{ secrets.CLUSTER_NAME }}
      - name: Deploy to DigitalOcean Kubernetes
        run:  |
            helm template $GITHUB_WORKSPACE/helm/. \
            --namespace=stage \
            --set image.tag=$IMAGE_TAG
            --set botToken=${{secrets.BOT_TOKEN}} | kubectl apply -f -
      - name: Verify deployment
        run: kubectl rollout status deployment/burger-termin
